<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>American_Health_E2C</fullName>
        <description>American Health E2C</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/American_Health_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Balance_Bar_E2C_AR</fullName>
        <description>Balance Bar E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Balance_Bar_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Body_Fortress_E2C_AR</fullName>
        <description>Body Fortress E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Body_Fortress_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Body_Fortress_W2C_AR</fullName>
        <description>Body Fortress W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Body_Fortress_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Email_to_Agent_when_Customer_Replies_to_an_Owned_Case</fullName>
        <description>Email to Agent when Customer Replies to an Owned Case</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>AR_Email_Templates/Notify_Agent_of_Customer_Response_to_Case</template>
    </alerts>
    <alerts>
        <fullName>Ester_C_E2C_AR</fullName>
        <description>Ester-C E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Ester_C_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Everclen_E2C_AR</fullName>
        <description>Everclen E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Everclen_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Flexamin_W2C_AR</fullName>
        <description>Flexamin W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Flexamin_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Good_N_Natural_E2C_AR</fullName>
        <description>Good N Natural E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Good_N_Natural_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Home_Health_E2C_AR</fullName>
        <description>Home Health E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Home_Health_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Met_Rx_E2C_AR</fullName>
        <description>Met-Rx E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Met_Rx_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Nature_s_Bounty_E2C_AR</fullName>
        <description>Nature&apos;s Bounty E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Natures_Bounty_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Osteo_Bi_Flex_E2C_AR</fullName>
        <description>Osteo Bi-Flex E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Sundown_Natural_Osteo_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Osteo_Bi_Flex_W2C_AR</fullName>
        <description>Osteo Bi-Flex W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Sundown_Natural_Osteo_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Perfectly_Pure_E2C_AR</fullName>
        <description>Perfectly Pure E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>AR_Email_Templates/Perfectly_Pure_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Perfectly_Pure_W2C_AR</fullName>
        <description>Perfectly Pure W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>AR_Email_Templates/Perfectly_Pure_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Pure_Protein_E2C_AR</fullName>
        <description>Pure Protein E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Pure_Protein_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Pure_Protein_W2C_AR</fullName>
        <description>Pure Protein W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>AR_Email_Templates/Pure_Protein_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Puritan_s_Pride_E2C_AR</fullName>
        <description>Puritan&apos;s Pride E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@puritan.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Puritan_s_Pride_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Puritan_s_Pride_ES_E2C_AR</fullName>
        <description>Puritan&apos;s Pride ES E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@puritan.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Puritan_s_Pride_E2C_AR_for_ES</template>
    </alerts>
    <alerts>
        <fullName>Puritan_s_Pride_W2C_Email</fullName>
        <description>Puritan&apos;s Pride W2C Email</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@puritan.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Puritan_s_Pride_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Rule_Nature_s_Bounty_W2C_AR</fullName>
        <description>Nature&apos;s Bounty W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>Reporter_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Natures_Bounty_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Solgar_E2C_AR</fullName>
        <description>Solgar E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Solgar_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Sundown_Naturals_E2C_AR</fullName>
        <description>Sundown Naturals E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Sundown_Natural_Osteo_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Sundown_Naturals_W2C_AR</fullName>
        <description>Sundown Naturals W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Consumer_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>noreply@customer-care-dept.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Sundown_Natural_Osteo_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Vitamin_World_E2C_AR</fullName>
        <description>Vitamin World E2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>Original_From__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@vitaminworld.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Vitamin_World_E2C_AR</template>
    </alerts>
    <alerts>
        <fullName>Vitamin_World_W2C_AR</fullName>
        <description>Vitamin World W2C AR</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@vitaminworld.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>AR_Email_Templates/Vitamin_World_W2C_AR</template>
    </alerts>
    <alerts>
        <fullName>ob_case_routing_debug</fullName>
        <ccEmails>jhaugh@acumensolutions.com</ccEmails>
        <description>ob case routing debug</description>
        <protected>false</protected>
        <senderType>CurrentUser</senderType>
        <template>AR_Email_Templates/ob_case_routing_debug</template>
    </alerts>
    <fieldUpdates>
        <fullName>CA_Escalated_for_QA_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Consumer_Affairs_Escalated_for_QA</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>CA Escalated for QA Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CA_Send_to_Supervisor</fullName>
        <field>OwnerId</field>
        <lookupValue>Consumer_Affairs_Sent_to_Supervisor</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>CA Send to Supervisor</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CA_Tech_Questions_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Consumer_Affairs_Tech_Questions</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>CA Tech Questions Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>PI_Escalated_for_QA_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Product_Information_Escalated_for_QA</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>PI Escalated for QA Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>PI_Sent_to_Supervisor_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Product_Information_Sent_to_Supervisor</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>PI Sent to Supervisor Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>PI_Tech_Questions_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Product_Information_Tech_Questions</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>PI Tech Questions Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Sent_to_Supervisor_Queue</fullName>
        <field>OwnerId</field>
        <lookupValue>Consumer_Affairs_Sent_to_Supervisor</lookupValue>
        <lookupValueType>Queue</lookupValueType>
        <name>Sent to Supervisor Queue</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Set_Priority_for_W2C</fullName>
        <field>Priority</field>
        <literalValue>Medium</literalValue>
        <name>Set Priority for W2C</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <outboundMessages>
        <fullName>CaseNewEmail</fullName>
        <apiVersion>27.0</apiVersion>
        <description>Case routing via b+s  Connector</description>
        <endpointUrl>http://10.208.8.89:8091/Case/</endpointUrl>
        <fields>Id</fields>
        <includeSessionId>true</includeSessionId>
        <integrationUser>ciscoivr@nbty.com</integrationUser>
        <name>CaseNewEmail</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <rules>
        <fullName>American Health E2C Confirmation</fullName>
        <actions>
            <name>American_Health_E2C</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>American Health</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Balance Bar E2C Confirmation</fullName>
        <actions>
            <name>Balance_Bar_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Balance Bar</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Body Fortress E2C Confirmation</fullName>
        <actions>
            <name>Body_Fortress_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Body Fortress</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Body Fortress W2C Confirmation</fullName>
        <actions>
            <name>Body_Fortress_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Body Fortress</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>CA - Escalate for QA</fullName>
        <actions>
            <name>CA_Escalated_for_QA_Queue</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Escalated__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Consumer Affairs</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CA - Sent to Supervisor</fullName>
        <actions>
            <name>CA_Send_to_Supervisor</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Consumer Affairs</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Send_to_Supervisor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CA - Tech Questions</fullName>
        <actions>
            <name>CA_Tech_Questions_Queue</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Tech_Questions__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Consumer Affairs</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Ester-C E2C Confirmation</fullName>
        <actions>
            <name>Ester_C_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Ester-C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Everclen E2C Confirmation</fullName>
        <actions>
            <name>Everclen_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Everclen</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Flexamin W2C Confirmation</fullName>
        <actions>
            <name>Flexamin_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Flexamin</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Good N Natural E2C Confirmation</fullName>
        <actions>
            <name>Good_N_Natural_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Good N&apos; Natural</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notEqual</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notEqual</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notEqual</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notEqual</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notEqual</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Home Health E2C Confirmation</fullName>
        <actions>
            <name>Home_Health_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Home Health</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Met-Rx E2C Confirmation</fullName>
        <actions>
            <name>Met_Rx_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Met-Rx</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Nature%27s Bounty E2C Confirmation</fullName>
        <actions>
            <name>Nature_s_Bounty_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Nature&apos;s Bounty</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Nature%27s Bounty W2C Confirmation</fullName>
        <actions>
            <name>Rule_Nature_s_Bounty_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Nature&apos;s Bounty</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Notify Agent When a Customer Replies to a Case</fullName>
        <actions>
            <name>Email_to_Agent_when_Customer_Replies_to_an_Owned_Case</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Status</field>
            <operation>equals</operation>
            <value>Customer Responded</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Osteo Bi-Flex E2C Confirmation</fullName>
        <actions>
            <name>Osteo_Bi_Flex_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Osteo Bi-Flex</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Osteo Bi-Flex W2C Confirmation</fullName>
        <actions>
            <name>Osteo_Bi_Flex_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Osteo Bi-Flex</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>PI - Escalated for QA</fullName>
        <actions>
            <name>PI_Escalated_for_QA_Queue</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Product Information</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Escalated__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>PI - Sent to Supervisor</fullName>
        <actions>
            <name>PI_Sent_to_Supervisor_Queue</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Product Information</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Send_to_Supervisor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>PI - Tech Questions</fullName>
        <actions>
            <name>PI_Tech_Questions_Queue</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Intake_Department__c</field>
            <operation>equals</operation>
            <value>Product Information</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Tech_Questions__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Perfectly Pure E2C Confirmation</fullName>
        <actions>
            <name>Perfectly_Pure_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Perfectly Pure</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>perfectlypure.com</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Perfectly Pure W2C Confirmation</fullName>
        <actions>
            <name>Perfectly_Pure_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Perfectly Pure</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Pure Protein E2C Confirmation</fullName>
        <actions>
            <name>Pure_Protein_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Pure Protein</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Pure Protein W2C Confirmation</fullName>
        <actions>
            <name>Pure_Protein_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Pure Protein</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Puritan%27s Pride  W2C Confirmation</fullName>
        <actions>
            <name>Puritan_s_Pride_W2C_Email</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Puritan&apos;s Pride</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Puritan%27s Pride E2C Confirmation</fullName>
        <actions>
            <name>Puritan_s_Pride_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Puritan&apos;s Pride</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Puritan%27s Pride ES E2C Confirmation</fullName>
        <actions>
            <name>Puritan_s_Pride_ES_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7 AND 8</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Puritan&apos;s Pride</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_To__c</field>
            <operation>contains</operation>
            <value>es.puritan.com</value>
        </criteriaItems>
        <description>For inbound spanish email addresses</description>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Set Priority if blank</fullName>
        <actions>
            <name>Set_Priority_for_W2C</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Solgar E2C Confirmation</fullName>
        <actions>
            <name>Solgar_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Solgar</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Sundown Naturals W2C Confirmation</fullName>
        <actions>
            <name>Sundown_Naturals_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Sundown Naturals</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>nbty.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.com</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.com.au</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritanspride.co.uk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Original_From__c</field>
            <operation>notContain</operation>
            <value>puritan.jp</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Vitamin World E2C Confirmation</fullName>
        <actions>
            <name>Vitamin_World_E2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Vitamin World</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Email to Case</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Vitamin World W2C Confirmation</fullName>
        <actions>
            <name>Vitamin_World_W2C_AR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Case.Brand__c</field>
            <operation>equals</operation>
            <value>Vitamin World</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Origin</field>
            <operation>equals</operation>
            <value>Web to Case</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>newUCCECase</fullName>
        <actions>
            <name>CaseNewEmail</name>
            <type>OutboundMessage</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 4 OR 5 OR 6 OR 7 OR 8)</booleanFilter>
        <criteriaItems>
            <field>Case.Status</field>
            <operation>equals</operation>
            <value>New</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Puritan&apos;s Pride - W2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Vitamin World - W2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Puritan&apos;s Pride - E2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Vitamin World - E2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Product Questions - W2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Perfectly Pure - E2C</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.OwnerId</field>
            <operation>equals</operation>
            <value>Perfectly Pure - W2C</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
</Workflow>
