/* 
	AddressValidatorTest
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	4/9/14		|	Created

*/
@isTest
global class AddressValidatorTest implements WebServiceMock {
	
	global void doInvoke(Object stub, Object request, Map<String, Object> response, String endpoint, String soapAction, String requestName, String responseNS, String responseName, String responseType){
		
		
		
		
		//response.put('response_x', response_x);
		
	}
}