NAME,PRODUCT_SUFFIX_C__C,COMPANY_CODE__C,MERCHANT_KEY__C,PICKLIST_BRAND__C,RECORDTYPENAME__C,SERVER_PREFIX__C,STATIC_IMAGE_URL__C,TENANTID__C,US_ONLY__C,WS_ID__C,BRAND_IMAGE__C,BACK_OFFICE_QUEUE__C
Perfectly_Pure_Customer,0021,PRFPR,DRMKEY1019,Perfectly Pure,Perfectly Pure,PR,http://images.vitaminimages.com/pp/VF/Assets/Puritan_products/,,TRUE,52,perfectlyPure_logo_small,BO - Perfectly Pure - Order
Puritans_Pride_Customer,0011,PP,DRMKEY1008,Puritan\'s Pride,Puritans Pride,PP,http://images.vitaminimages.com/pp/VF/Assets/Puritan_products/,24,FALSE,1,Puritan_small_logo,BO - Puritan\'s Pride - Order
Vitamin_World_Customer,0070,VW,DRMKEY1014,Vitamin World,Vitamin World,VW,http://images.vitaminimages.com/vw/VF/Assets/VitaminWorld_Products/,43,FALSE,5,VW_small_logo,BO - Vitamin World - Order
