NAME,CURRENCYISOCODE,CURRENCY_CODE__C,DESCRIPTION__C,RECORD_TYPE_NAME__C,PRODUCT_SUFFIX__C
1,USD,USD,Puritan.com,Puritan's Pride,0011
18,USD,JPY,Puritan.jp,Puritan's Pride,0011
45,USD,GBP,Puritanspride.co.uk,Puritan's Pride,0011
47,USD,AUD,Puritan.au,Puritan's Pride,0011
5,USD,USD,Vitaminworld.com,Vitamin World,0070
6,USD,GBP,HollandandBarrett.com,,
17,USD,USD,metrx.com,Met-RX Customer,
50,USD,USD,gnnbar.com,,
